spring:
  application:
    name: screenmatch
  datasource:
    url: jdbc:postgresql://localhost/alura_series
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
hibernate:
  dialect: org.hibernate.dialect.HSQLDialect

